robot:
  name: "ur5"
  joints: ['ur5_shoulder_pan_joint', 'ur5_shoulder_lift_joint',
            'ur5_elbow_joint', 'ur5_wrist_1_joint', 'ur5_wrist_2_joint',
            'ur5_wrist_3_joint']
  ee_link: "tool_link"
  urdf: "../assets/ur5e.urdf"
